// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiRsGMARDselQ8NEelHtJnBde5uWsD1Bk',
    appId: '1:789440799203:web:f85bdf1f71f333f4f580d6',
    messagingSenderId: '789440799203',
    projectId: 'barber-appointment-94d83',
    authDomain: 'barber-appointment-94d83.firebaseapp.com',
    storageBucket: 'barber-appointment-94d83.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Qr9nhiudNpskkTQssQRN4CIgHT4J4T8',
    appId: '1:789440799203:android:69949cf16640b678f580d6',
    messagingSenderId: '789440799203',
    projectId: 'barber-appointment-94d83',
    storageBucket: 'barber-appointment-94d83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZQHM09tUnQa4y26G2eyuav7D60ryHSXo',
    appId: '1:789440799203:ios:9ba256d69077d21ef580d6',
    messagingSenderId: '789440799203',
    projectId: 'barber-appointment-94d83',
    storageBucket: 'barber-appointment-94d83.firebasestorage.app',
    iosBundleId: 'com.example.barberAppointment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZQHM09tUnQa4y26G2eyuav7D60ryHSXo',
    appId: '1:789440799203:ios:9ba256d69077d21ef580d6',
    messagingSenderId: '789440799203',
    projectId: 'barber-appointment-94d83',
    storageBucket: 'barber-appointment-94d83.firebasestorage.app',
    iosBundleId: 'com.example.barberAppointment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiRsGMARDselQ8NEelHtJnBde5uWsD1Bk',
    appId: '1:789440799203:web:98ea5a2620186b91f580d6',
    messagingSenderId: '789440799203',
    projectId: 'barber-appointment-94d83',
    authDomain: 'barber-appointment-94d83.firebaseapp.com',
    storageBucket: 'barber-appointment-94d83.firebasestorage.app',
  );

}